"use client";
import { useState } from "react";
import { ArrowUp, Check, CalendarDays, Users, ChevronLeft, MoreHorizontal, Plus } from "lucide-react";
const examples = {
  coffee: { label: "Кафе", brand: "Смена", tagline: "Кофе по пути", heading: "Ваше утро.\nВаш кофе.", prompt: "Сделай приложение кофейни: меню, заказ к выдаче и бонусы для гостей.", result: "Меню, корзина и заказ — в одном приложении.", action: "Перейти к заказу" },
  services: { label: "Услуги", brand: "Форма", tagline: "Студия движения", heading: "Время\nдля себя.", prompt: "Хочу приложение студии йоги: расписание, запись на занятия и личный кабинет.", result: "Клиент выбирает занятие и записывается сам.", action: "Выберите время" },
  community: { label: "Сообщество", brand: "Круг", tagline: "Клуб близких по духу", heading: "Собираемся\nна интересное.", prompt: "Создай приложение клуба: ближайшие встречи, материалы и регистрация участников.", result: "События и материалы доступны участникам в MAX.", action: "Смотреть встречи" },
} as const;
export function LandingExample() {
  const [selected, setSelected] = useState<keyof typeof examples>("coffee"); const example = examples[selected];
  return <figure className="ml-demo" data-testid="landing-example">
    <div className="ml-demo-tabs" role="group" aria-label="Примеры приложений">{Object.entries(examples).map(([key,item])=><button key={key} type="button" aria-pressed={selected === key} data-marketing="scenario_select" data-placement={key} onClick={()=>setSelected(key as keyof typeof examples)}>{item.label}</button>)}</div>
    <div className="ml-demo-workspace"><div className="ml-demo-chat"><span className="ml-demo-label">ВЫ ОПИСЫВАЕТЕ</span><p>{example.prompt}</p><span className="ml-demo-send"><ArrowUp size={17}/></span><div className="ml-demo-reply"><Check size={15}/><span>{example.result}</span></div></div>
      <div className={`ml-phone ml-phone--${selected}`} aria-live="polite"><div className="ml-phone-top"><ChevronLeft size={16}/><strong>{example.brand}</strong><MoreHorizontal size={17}/></div><div className="ml-phone-content"><span className="ml-phone-tag">{example.tagline}</span><h3>{example.heading}</h3>
        {selected === "coffee" ? <><div className="ml-coffee-art" aria-hidden="true"><svg viewBox="0 0 220 160"><ellipse cx="110" cy="141" rx="66" ry="9" fill="#d5c8b7"/><path d="M140 61h20c37 0 33 47-3 47h-14" fill="none" stroke="#fafafa" strokeWidth="12"/><path d="M54 48h102l-9 69c-3 23-78 23-82 0z" fill="#faf8f2"/><ellipse cx="105" cy="49" rx="51" ry="13" fill="#e9e0d4"/><ellipse cx="105" cy="49" rx="43" ry="9" fill="#745341"/><path d="M82 49c12-13 36-13 47 0-15 10-32 10-47 0" fill="#ded4c4"/><path d="M105 40v18" stroke="#f5f2eb" strokeWidth="2"/></svg><span>Сварим к вашему приходу</span></div><div className="ml-phone-item"><div><strong>Капучино</strong><small>Мягкий, с молочной пеной · 250 мл</small></div><Plus size={18}/></div><div className="ml-phone-item"><div><strong>Флэт уайт</strong><small>Больше кофе, меньше молока</small></div><Plus size={18}/></div></> : selected === "services" ? <><div className="ml-schedule-art"><span>ПОНЕДЕЛЬНИК, 21 СЕНТЯБРЯ</span><strong>Практика<br/>в своём ритме</strong><CalendarDays size={36}/></div><div className="ml-phone-item"><div><strong>09:00 · Утренняя йога</strong><small>60 минут · Для любого уровня</small></div></div><div className="ml-phone-item"><div><strong>18:30 · Здоровая спина</strong><small>45 минут · Мягкая практика</small></div></div></> : <><div className="ml-community-art"><Users size={44}/><strong>Хорошие идеи<br/>начинаются со встречи.</strong></div><div className="ml-phone-item"><div><strong>Субботний книжный клуб</strong><small>26 сентября · 12:00</small></div></div><div className="ml-phone-item"><div><strong>Материалы для участников</strong><small>Всё важное под рукой</small></div></div></>}
        <div className="ml-phone-action">{example.action}</div></div></div></div>
    <figcaption>Пример интерфейса · иллюстрация возможностей, не клиентский проект</figcaption>
  </figure>;
}
