import { ArrowRight, Check, MessageSquareText, MousePointer2, History, SlidersHorizontal, ChevronRight } from "lucide-react";
import Link from "next/link";
import "@/components/max/max-studio.css";
import "./max-public.css";
import "./max-landing.css";
import { BrandMark } from "./BrandMark";
import { LandingExample } from "./LandingExample";
import { LandingUseCases } from "./LandingUseCases";
import { MarketingEvents } from "./MarketingEvents";

const faqs = [
  ["code", "Я не программист. У меня получится?", "Начните с того, что должен сделать ваш клиент: выбрать товар, записаться или открыть материал. Пошаговый опрос поможет описать задачу. Yleum соберёт приложение, а вы проверите его и попросите изменения обычным сообщением."],
  ["free", "Что значит «начать бесплатно»?", "Вы регистрируетесь на тарифе Free без оплаты и привязки карты. Генерация расходует доступный баланс; лимиты и условия публикации зависят от тарифа. Актуальные условия вы увидите в аккаунте до оплаты. Free — не обещание безлимитной генерации или бесплатного публичного хостинга."],
  ["max", "Бот MAX нужен сразу?", "Нет. Сначала можно описать идею и работать над приложением. Для запуска внутри MAX нужно создать бота в кабинете MAX, пройти необходимые проверки на стороне платформы и подключить его в Yleum. Помощник проведёт по шагам."],
  ["change", "Можно менять приложение после запуска?", "Да. Продолжайте работу в редакторе, проверяйте новую версию и публикуйте обновление, когда готовы. История версий помогает посмотреть предыдущий результат."],
  ["payments", "Можно добавить оплату и другие сервисы?", "В Yleum есть раздел интеграций. Доступность конкретного сервиса зависит от его поддержки и вашего тарифа. Подключение платёжного провайдера и его условия оформляются отдельно — сама генерация приложения не подключает приём платежей автоматически."],
  ["ready", "Что проверить перед публикацией?", "Пройдите путь своего клиента в предпросмотре, проверьте тексты, формы и нужные функции. Затем выполните обязательные пункты в окне запуска. Созданный ИИ результат требует вашей проверки перед тем, как им начнут пользоваться клиенты."],
] as const;

function Signup({ placement, children = "Начать бесплатно" }: { placement: string; children?: React.ReactNode }) {
  return <Link href="/max/register" className="max-public-button max-public-button--primary" data-marketing="signup_click" data-placement={placement}>{children}<ArrowRight size={18}/></Link>;
}

export function MaxPublicLanding() {
  return <main data-max-studio className="max-public ml-landing">
    <MarketingEvents page="landing"/>
    <a className="ml-skip" href="#main-content">К содержимому</a>
    <header className="max-public-header"><div className="max-public-header__inner"><div className="max-public-header__brand"><BrandMark/></div><nav aria-label="Разделы страницы"><a href="#examples">Для вашего бизнеса</a><a href="#process">Как работает</a><a href="#free">Бесплатный старт</a><a href="#faq">Вопросы</a></nav><div className="max-public-header__actions"><Link className="max-public-link" href="/login?next=/max" data-marketing="login_click" data-placement="header">Войти</Link><Signup placement="header"/></div></div></header>
    <section id="main-content" className="ml-wrap ml-hero" data-marketing-section="hero"><div className="ml-hero-copy"><p className="ml-eyebrow"><span/>YLEUM</p><h1>Ваш бизнес.<br/>Ваше приложение.<br/><em>Внутри MAX.</em></h1><p className="ml-lead">Меню, запись на услуги или клуб для клиентов. Опишите идею — ИИ соберёт приложение, которое вы сможете менять без кода.</p><div className="ml-actions"><Signup placement="hero"/><a className="ml-demo-link" href="#examples">Посмотреть примеры <ChevronRight size={16}/></a></div><p className="ml-caption">Тариф Free · Без привязки карты</p></div><LandingExample/></section>
    <div className="ml-wrap ml-value-strip"><span><Check/>Не нужно писать код</span><span><Check/>Правки в диалоге</span><span><Check/>Предпросмотр до запуска</span><span><Check/>Приложение внутри MAX</span></div>
    <LandingUseCases/>
    <section className="ml-editor-section" id="benefits" data-marketing-section="editor"><div className="ml-wrap ml-editor-layout"><div className="ml-section-head"><p className="ml-eyebrow">ВЫ УПРАВЛЯЕТЕ РЕЗУЛЬТАТОМ</p><h2>Как объяснить<br/>разработчику.<br/><em>Только прямо в чате.</em></h2><p>Не нужно разбираться в настройках до первого результата. Сформулируйте задачу, посмотрите приложение и уточните, что изменить.</p><Signup placement="editor"/></div><div className="ml-editor-proof"><div className="ml-editor-top"><span><span className="ml-status-dot"/>Редактор</span><span>Чат + предпросмотр</span></div><div className="ml-editor-message"><MessageSquareText size={18}/><p>Добавь поиск по меню и сделай кнопку заказа заметнее.</p></div><div className="ml-editor-response"><Check size={17}/><p>Проверьте изменения в предпросмотре.<small>Иллюстрация работы редактора</small></p></div><ul>{[[MousePointer2,"Проверяйте как клиент","Открывайте экраны и проходите нужный сценарий."],[History,"Сохраняйте историю","Сравнивайте результат с предыдущими версиями."],[SlidersHorizontal,"Уточняйте постепенно","Меняйте оформление, тексты и функции в ходе работы."]].map(([Icon,title,text])=> { const I=Icon as typeof History;return <li key={String(title)}><I size={20}/><div><h3>{String(title)}</h3><p>{String(text)}</p></div></li>;})}</ul></div></div></section>
    <section id="process" className="ml-wrap ml-section" data-marketing-section="process"><div className="ml-section-head"><p className="ml-eyebrow">ОТ ИДЕИ ДО КЛИЕНТОВ</p><h2>Понятный следующий шаг.<br/>На каждом этапе.</h2></div><ol className="ml-steps">{[["Опишите идею","Короткий опрос поможет выбрать задачу, аудиторию и нужные функции."],["Соберите и проверьте","Получите версию приложения. Пройдите сценарий и попросите нужные правки."],["Подключите MAX","Помощник покажет, как создать бота, подключить его и подготовить запуск."],["Опубликуйте","Получите адрес и добавьте его в MAX. Возвращайтесь в редактор за обновлениями."]].map(([title,text],i)=><li key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol><p className="ml-process-note">До публикации приложение проверяете вы. Подключение MAX и публичный запуск — отдельные шаги, не автоматическое действие.</p></section>
    <section id="free" className="ml-wrap ml-section ml-free" data-marketing-section="free"><div className="ml-section-head"><p className="ml-eyebrow">СНАЧАЛА ПОПРОБУЙТЕ</p><h2>Большая идея.<br/>Бесплатный первый шаг.</h2><p>Создайте аккаунт на Free, познакомьтесь с Yleum и опишите свой проект. Решение о платных возможностях можно принять позже.</p></div><div className="ml-free-plan"><div className="ml-free-plan-top"><span>FREE</span><span>Без привязки карты</span></div><p className="ml-price">0 ₽<span>за тариф</span></p><ul><li><Check/>Личное рабочее пространство</li><li><Check/>Пошаговое описание проекта</li><li><Check/>Доступ к редактору в рамках лимитов</li></ul><Signup placement="free">Зарегистрироваться бесплатно</Signup><p className="ml-free-terms">Генерация расходует баланс. Публикация и дополнительные возможности зависят от тарифа. Условия и доступные лимиты — в аккаунте до оплаты.</p></div></section>
    <section id="faq" className="ml-wrap ml-section ml-faq-layout" data-marketing-section="faq"><div className="ml-section-head"><p className="ml-eyebrow">БЕЗ НЕЯСНОСТЕЙ</p><h2>Хорошие вопросы.<br/>Прямые ответы.</h2><Link href="/max/guide" className="ml-guide" data-marketing="guide_click" data-placement="faq">Открыть руководство <ArrowRight size={17}/></Link></div><div className="ml-faq">{faqs.map(([id,question,answer])=><details key={id} data-faq={id}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="ml-bottom" data-marketing-section="final"><div className="ml-wrap"><p className="ml-eyebrow">ВАША ИДЕЯ — СЛЕДУЮЩАЯ</p><h2>Что ваши клиенты<br/>смогут сделать в MAX?</h2><p>Начните с одного полезного сценария. Yleum поможет превратить его в приложение.</p><Signup placement="final"/><small>Регистрация на Free · Без привязки карты</small></div></section>
    <footer className="max-public-footer"><div><div className="ml-footer-brand"><BrandMark/><span>Yleum — приложения для вашего бизнеса.</span><small>© {new Date().getFullYear()} Yleum (произносится «Илиум»). Не является официальным продуктом MAX.</small></div><nav aria-label="Информация о продукте"><Link href="/max/guide">Руководство</Link><Link href="/contact">Контакты</Link><Link href="/legal/terms">Условия</Link><Link href="/legal/privacy">Конфиденциальность</Link><Link href="/requisites">Реквизиты</Link></nav></div></footer>
  </main>;
}
