#!/usr/bin/env bash
# WireGuard-mesh между тремя VPS (поверх приватной LAN 172.197.102.0/24).
# Две фазы: `keygen` (создать ключ, напечатать публичный) и `configure` (собрать wg0 с пирами).
#
#   keygen
#   configure NAME WG_IP WG_PORT LAN_IFACE "peer1:pubkey:lan_ip:wg_ip peer2:..."
set -euo pipefail
MODE=$1; shift
umask 077
install -d -m 700 /etc/wireguard

case "$MODE" in
  keygen)
    [ -s /etc/wireguard/private.key ] || wg genkey > /etc/wireguard/private.key
    wg pubkey < /etc/wireguard/private.key > /etc/wireguard/public.key
    cat /etc/wireguard/public.key
    ;;
  configure)
    NAME=$1 WG_IP=$2 WG_PORT=$3 LAN_IFACE=$4 PEERS=$5
    LAN_MTU=$(cat "/sys/class/net/$LAN_IFACE/mtu")
    WG_MTU=$((LAN_MTU - 80))
    {
      echo "# generated by infra/max-k3s/remote/10-wireguard.sh — не править руками"
      echo "[Interface]"
      echo "Address = $WG_IP/24"
      echo "ListenPort = $WG_PORT"
      echo "MTU = $WG_MTU"
      echo "PrivateKey = $(cat /etc/wireguard/private.key)"
      for p in $PEERS; do
        IFS=: read -r pname ppub plan pwg <<< "$p"
        echo
        echo "[Peer]"
        echo "# $pname"
        echo "PublicKey = $ppub"
        echo "AllowedIPs = $pwg/32"
        echo "Endpoint = $plan:$WG_PORT"
        echo "PersistentKeepalive = 25"
      done
    } > /etc/wireguard/wg0.conf
    chmod 600 /etc/wireguard/wg0.conf
    systemctl enable wg-quick@wg0 >/dev/null
    if systemctl is-active -q wg-quick@wg0; then
      wg syncconf wg0 <(wg-quick strip wg0)
      ip addr show wg0 | grep -q "$WG_IP/24" || { systemctl restart wg-quick@wg0; }
    else
      systemctl start wg-quick@wg0
    fi
    # node-exporter слушает только на WG-адресе (Prometheus на core ходит по mesh)
    cat > /etc/default/prometheus-node-exporter <<EOF
ARGS="--web.listen-address=$WG_IP:9100 --collector.systemd --collector.processes"
EOF
    systemctl enable --now prometheus-node-exporter >/dev/null
    systemctl restart prometheus-node-exporter
    for p in $PEERS; do
      IFS=: read -r pname ppub plan pwg <<< "$p"
      if ping -c 2 -W 2 "$pwg" >/dev/null 2>&1; then echo "WG $NAME -> $pname ($pwg): OK"; else echo "WG $NAME -> $pname ($pwg): FAIL"; fi
    done
    wg show wg0 | grep -E "interface|peer|handshake" | sed 's/^/  /'
    ;;
  *) echo "usage: keygen | configure ..." >&2; exit 1 ;;
esac
