#!/usr/bin/env bash
# Одно-нодовый K3s-кластер на этой VPS (server + worker в одном процессе, как в целевой
# схеме: три изолированных control plane — Core / Runtime / Commerce).
#
# Аргументы: NAME PUBLIC_IP LAN_IP WG_IP CLUSTER_CIDR SERVICE_CIDR CLUSTER_DNS DOMAIN K3S_VERSION ADMIN_USER
set -euo pipefail
NAME=$1 PUBLIC_IP=$2 LAN_IP=$3 WG_IP=$4 CLUSTER_CIDR=$5 SERVICE_CIDR=$6 CLUSTER_DNS=$7 DOMAIN=$8 K3S_VERSION=$9 ADMIN_USER=${10}

install -d -m 755 /etc/rancher/k3s
cat > /etc/rancher/k3s/config.yaml <<EOF
# generated by infra/max-k3s/remote/20-k3s.sh — кластер "$NAME"
node-name: $NAME
node-ip: $WG_IP
node-external-ip: $PUBLIC_IP
# Публичный IP у Serverum — 1:1 NAT: без явного advertise-address поды идут к API через
# шлюз провайдера (hairpin) и упираются в ufw. Анонсируем API по WG-адресу.
advertise-address: $WG_IP
flannel-iface: wg0
cluster-cidr: $CLUSTER_CIDR
service-cidr: $SERVICE_CIDR
cluster-dns: $CLUSTER_DNS
cluster-domain: cluster.local
tls-san:
  - $PUBLIC_IP
  - $LAN_IP
  - $WG_IP
  - $NAME.$DOMAIN
  - k8s-$NAME.$DOMAIN
write-kubeconfig-mode: "0640"
secrets-encryption: true
node-label:
  - max.studio/cluster=$NAME
kubelet-arg:
  - max-pods=200
EOF

NEW_HASH=$(sha256sum /etc/rancher/k3s/config.yaml | cut -c1-16)
OLD_HASH=$(cat /etc/rancher/k3s/.config.applied 2>/dev/null || true)
if ! command -v k3s >/dev/null || [ "$(k3s --version | awk 'NR==1{print $3}')" != "$K3S_VERSION" ]; then
  echo "== [$NAME] устанавливаю k3s $K3S_VERSION"
  curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="$K3S_VERSION" INSTALL_K3S_SKIP_ENABLE=false sh -s - server
elif [ "$NEW_HASH" != "$OLD_HASH" ]; then
  echo "== [$NAME] k3s $K3S_VERSION уже установлен, config.yaml изменился — перезапускаю"
  systemctl restart k3s
else
  echo "== [$NAME] k3s $K3S_VERSION уже установлен, конфиг без изменений"
fi
echo "$NEW_HASH" > /etc/rancher/k3s/.config.applied

echo "== [$NAME] жду Ready"
for i in $(seq 1 60); do
  if k3s kubectl get node "$NAME" 2>/dev/null | grep -q " Ready"; then break; fi
  sleep 5
done
k3s kubectl get node -o wide
chgrp "$ADMIN_USER" /etc/rancher/k3s/k3s.yaml
# helm/kubectl для администратора на самом хосте
grep -q KUBECONFIG /home/$ADMIN_USER/.bashrc || echo 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' >> /home/$ADMIN_USER/.bashrc

echo "== [$NAME] жду системные поды (traefik, coredns, local-path, metrics)"
for i in $(seq 1 90); do
  total=$(k3s kubectl get pods -n kube-system --no-headers 2>/dev/null | wc -l | tr -d ' ')
  pending=$(k3s kubectl get pods -n kube-system --no-headers 2>/dev/null | grep -vcE "Running|Completed" || true)
  if [ "$total" -ge 5 ] && [ "$pending" = "0" ] && k3s kubectl get svc -n kube-system traefik >/dev/null 2>&1; then break; fi
  sleep 5
done
k3s kubectl get pods -n kube-system -o wide | sed 's/^/  /'
k3s kubectl get svc -n kube-system traefik | sed 's/^/  /'
echo "K3S_DONE $NAME $(k3s --version | head -1)"
