#!/usr/bin/env bash
# Хостовый PostgreSQL 16 на VPS (по схеме: у каждого кластера своя база, вне K3s).
# Слушает 127.0.0.1 и WG-адрес; доступ по scram из WG-сети и из подов этого кластера.
# Создаёт роль/базу кластера, пишет DSN в /etc/max-studio/postgres.env (root, 0600),
# ставит ночной бэкап (pg_dump всех баз + state K3s) в /var/backups/max-studio.
#
# Аргументы: NAME WG_IP WG_NET CLUSTER_CIDR DBNAME DBUSER
set -euo pipefail
NAME=$1 WG_IP=$2 WG_NET=$3 CLUSTER_CIDR=$4 DBNAME=$5 DBUSER=$6
export DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a
PGVER=16
CONF_D=/etc/postgresql/$PGVER/main/conf.d
HBA=/etc/postgresql/$PGVER/main/pg_hba.conf

echo "== [$NAME] postgresql-$PGVER"
apt-get install -y -q --no-install-recommends postgresql-$PGVER postgresql-contrib-$PGVER postgresql-client-$PGVER >/dev/null

MEM_GB=$(awk '/MemTotal/ {printf "%d", $2/1024/1024}' /proc/meminfo)
SHARED=$((MEM_GB / 8))GB         # 31G → 3GB; поверх ещё живёт K3s, не жадничаем
EFFECTIVE=$((MEM_GB / 2))GB
cat > "$CONF_D/10-max.conf" <<EOF
# generated by infra/max-k3s/remote/40-postgres.sh
listen_addresses = '127.0.0.1,$WG_IP'
max_connections = 200
shared_buffers = $SHARED
effective_cache_size = $EFFECTIVE
work_mem = 32MB
maintenance_work_mem = 512MB
wal_level = replica
max_wal_size = 2GB
min_wal_size = 512MB
checkpoint_completion_target = 0.9
random_page_cost = 1.1
effective_io_concurrency = 200
password_encryption = scram-sha-256
log_min_duration_statement = 500
log_line_prefix = '%m [%p] %u@%d '
timezone = 'UTC'
EOF

if ! grep -q "max-k3s" "$HBA"; then
  cat >> "$HBA" <<EOF

# max-k3s: WG-сеть между VPS и поды локального K3s-кластера (пароли scram)
host    all    all    $WG_NET         scram-sha-256
host    all    all    $CLUSTER_CIDR   scram-sha-256
EOF
fi
systemctl enable postgresql >/dev/null
systemctl restart postgresql
for i in $(seq 1 20); do pg_isready -q -h 127.0.0.1 && break; sleep 2; done
pg_isready -q -h 127.0.0.1 || { echo "POSTGRES_FAILED $NAME: сервер не поднялся"; tail -5 /var/log/postgresql/postgresql-$PGVER-main.log; exit 1; }

ENV=/etc/max-studio/postgres.env
install -d -m 700 /etc/max-studio
if [ -f "$ENV" ] && grep -q "^PG_PASSWORD=" "$ENV"; then
  PW=$(sed -n 's/^PG_PASSWORD=//p' "$ENV")
else
  PW=$(openssl rand -base64 30 | tr -d '/+=' | cut -c1-32)
fi
cd /tmp
if ! sudo -u postgres psql -tAc "select 1 from pg_roles where rolname='$DBUSER'" | grep -q 1; then
  sudo -u postgres psql -qc "create role $DBUSER login password '$PW'"
else
  sudo -u postgres psql -qc "alter role $DBUSER password '$PW'"
fi
if ! sudo -u postgres psql -tAc "select 1 from pg_database where datname='$DBNAME'" | grep -q 1; then
  sudo -u postgres createdb -O "$DBUSER" "$DBNAME"
fi
umask 077
cat > "$ENV" <<EOF
# generated by infra/max-k3s/remote/40-postgres.sh — креды базы кластера "$NAME"
PG_HOST=$WG_IP
PG_PORT=5432
PG_DB=$DBNAME
PG_USER=$DBUSER
PG_PASSWORD=$PW
PG_DSN=postgresql://$DBUSER:$PW@$WG_IP:5432/$DBNAME
EOF
chmod 600 "$ENV"
PGPASSWORD=$PW psql -h "$WG_IP" -U "$DBUSER" -d "$DBNAME" -tAc "select 'PG_LOGIN_OK ' || version()" | cut -c1-40

echo "== [$NAME] ночной бэкап (03:15 MSK): все базы + state K3s, хранить 14 дней"
install -d -m 700 /var/backups/max-studio
cat > /usr/local/bin/max-backup.sh <<'EOF'
#!/usr/bin/env bash
# Локальный бэкап VPS: pg_dumpall (роли) + pg_dump -Fc каждой базы + state K3s + конфиги.
set -euo pipefail
ROOT=/var/backups/max-studio
DAY=$(date +%F)
DEST=$ROOT/$DAY
install -d -m 700 "$DEST"
cd /tmp
sudo -u postgres pg_dumpall --globals-only | gzip > "$DEST/globals.sql.gz"
for db in $(sudo -u postgres psql -tAc "select datname from pg_database where not datistemplate and datname<>'postgres'"); do
  sudo -u postgres pg_dump -Fc "$db" > "$DEST/$db.dump"
done
# K3s: sqlite-state + токен + конфиги (восстановление: остановить k3s, вернуть каталог, запустить)
if [ -d /var/lib/rancher/k3s/server/db ]; then
  tar -C / -czf "$DEST/k3s-state.tgz" var/lib/rancher/k3s/server/db var/lib/rancher/k3s/server/token etc/rancher/k3s 2>/dev/null || true
fi
tar -C / -czf "$DEST/etc-max-studio.tgz" etc/max-studio etc/wireguard etc/ssh/sshd_config.d etc/ssh/authorized_keys.d 2>/dev/null || true
find "$ROOT" -mindepth 1 -maxdepth 1 -type d -mtime +14 -exec rm -rf {} +
du -sh "$DEST" | awk '{print "backup " $2 ": " $1}'
EOF
chmod 700 /usr/local/bin/max-backup.sh
cat > /etc/systemd/system/max-backup.service <<'EOF'
[Unit]
Description=MAX Studio nightly backup (postgres + k3s state)
[Service]
Type=oneshot
ExecStart=/usr/local/bin/max-backup.sh
Nice=10
IOSchedulingClass=idle
EOF
cat > /etc/systemd/system/max-backup.timer <<'EOF'
[Unit]
Description=MAX Studio nightly backup timer
[Timer]
OnCalendar=*-*-* 03:15:00 Europe/Moscow
RandomizedDelaySec=10m
Persistent=true
[Install]
WantedBy=timers.target
EOF
systemctl daemon-reload
systemctl enable --now max-backup.timer >/dev/null
/usr/local/bin/max-backup.sh
echo "POSTGRES_DONE $NAME"
