#!/usr/bin/env bash
# Перекрёстные копии ночных бэкапов между VPS по WireGuard: потеря одной VPS ≠ потеря данных.
# Приёмник — системный пользователь backupsync, ключ ограничен `rrsync -wo <каталог>` (только запись
# в свой подкаталог, без шелла). Отправитель — root этой VPS после max-backup.service.
#
#   keygen                              — пользователь-приёмник + root-ключ для push; печатает публичный ключ
#   authorize NAME PUBKEY               — разрешить хосту NAME класть копии в /var/backups/max-studio-peer/NAME
#   schedule TARGET_NAME TARGET_WG_IP   — после ночного бэкапа rsync'ить /var/backups/max-studio на TARGET
set -euo pipefail
MODE=$1; shift
PEER_ROOT=/var/backups/max-studio-peer
KEYS=/etc/ssh/authorized_keys.d/backupsync

case "$MODE" in
  keygen)
    id backupsync >/dev/null 2>&1 || useradd --system --home-dir "$PEER_ROOT" --shell /bin/sh --create-home backupsync
    install -d -m 750 -o backupsync -g backupsync "$PEER_ROOT"
    install -d -m 700 /root/.ssh
    [ -s /root/.ssh/id_ed25519 ] || ssh-keygen -q -t ed25519 -N '' -C "backup-push@$(hostname)" -f /root/.ssh/id_ed25519
    cat /root/.ssh/id_ed25519.pub
    ;;
  authorize)
    NAME=$1 PUB=$2
    install -d -m 750 -o backupsync -g backupsync "$PEER_ROOT/$NAME"
    touch "$KEYS"; chmod 644 "$KEYS"
    sed -i "/ backup-push@$NAME\$/d" "$KEYS"
    echo "command=\"/usr/bin/rrsync -wo $PEER_ROOT/$NAME\",restrict $PUB" >> "$KEYS"
    echo "authorize: $NAME → $PEER_ROOT/$NAME"
    ;;
  schedule)
    TARGET=$1 TARGET_WG=$2
    cat > /usr/local/bin/max-backup-push.sh <<EOF
#!/usr/bin/env bash
# generated by infra/max-k3s/remote/50-backup-sync.sh — копия локальных бэкапов на $TARGET по WireGuard
set -euo pipefail
rsync -a --delete -e "ssh -i /root/.ssh/id_ed25519 -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15" \\
  /var/backups/max-studio/ backupsync@$TARGET_WG:/
echo "backup push → $TARGET: ok (\$(du -sh /var/backups/max-studio | cut -f1))"
EOF
    chmod 700 /usr/local/bin/max-backup-push.sh
    install -d /etc/systemd/system/max-backup.service.d
    printf '[Service]\nExecStartPost=/usr/local/bin/max-backup-push.sh\n' > /etc/systemd/system/max-backup.service.d/push.conf
    systemctl daemon-reload
    /usr/local/bin/max-backup-push.sh
    ;;
  *) echo "usage: keygen | authorize NAME PUBKEY | schedule TARGET_NAME TARGET_WG_IP" >&2; exit 1 ;;
esac
