"""AV04: ordinary CHECK/DEFAULT/SERIAL/IDENTITY are described, not refused;
genuinely unmodeled objects are named precisely and still stop a direct restore."""

from __future__ import annotations

import json

import pytest

from tests._versioning_pg import pg  # noqa: F401
from yleum_orchestrator.services.restoration_catalog import (
    CATALOG_SQL,
    describe_catalog,
    ordinary_default,
)
from yleum_orchestrator.services.restoration_data_contract import (
    DataContract,
    assess_contract,
    normalize_check,
)


def live(pg):  # noqa: F811
    return describe_catalog(json.loads(pg.run(CATALOG_SQL)))


def test_common_generated_schema_has_no_blockers(pg):  # noqa: F811
    pg.run("""
      CREATE TABLE clients (
        id serial PRIMARY KEY,
        code integer GENERATED BY DEFAULT AS IDENTITY,
        uid uuid NOT NULL DEFAULT gen_random_uuid(),
        name varchar(120) NOT NULL,
        status text NOT NULL DEFAULT 'new',
        tags text[] NOT NULL DEFAULT '{}'::text[],
        meta jsonb NOT NULL DEFAULT '{}'::jsonb,
        balance numeric(12,2) NOT NULL DEFAULT 0,
        score integer DEFAULT (-1),
        active boolean NOT NULL DEFAULT true,
        created_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT clients_status_check CHECK (status IN ('new', 'vip')),
        CONSTRAINT clients_balance_check CHECK (balance >= 0)
      );
    """)
    contract, blockers, unsupported = live(pg)
    assert blockers == [] and unsupported == []
    table = contract.tables[0]
    assert {check.name for check in table.check_constraints} == {
        "clients_balance_check", "clients_status_check",
    }
    columns = {column.name: column for column in table.columns}
    assert columns["code"].identity == "by_default"
    assert columns["id"].default and columns["id"].default.startswith("nextval(")
    assert columns["status"].default == "'new'::text"


@pytest.mark.parametrize(
    "statement,kind,obj",
    [
        (
            "CREATE FUNCTION public.mint_code() RETURNS text LANGUAGE sql AS $$SELECT 'x'$$; "
            "ALTER TABLE clients ADD COLUMN code text DEFAULT public.mint_code()",
            "default", "public.clients.code",
        ),
        (
            "CREATE FUNCTION public.touch() RETURNS trigger LANGUAGE plpgsql AS "
            "$$BEGIN RETURN NEW; END$$; CREATE TRIGGER touch_clients BEFORE UPDATE ON clients "
            "FOR EACH ROW EXECUTE FUNCTION public.touch()",
            "trigger", "public.clients.touch_clients",
        ),
        (
            "CREATE UNIQUE INDEX clients_lower_name ON clients (lower(name))",
            "index", "public.clients.clients_lower_name",
        ),
        (
            "ALTER TABLE clients ADD CONSTRAINT clients_name_len "
            "CHECK (length(name) > 0) NOT VALID",
            "constraint", "public.clients.clients_name_len",
        ),
    ],
)
def test_unmodeled_objects_are_named_precisely(pg, statement, kind, obj):  # noqa: F811
    pg.run("CREATE TABLE clients (id serial PRIMARY KEY, name text);")
    pg.run(statement + ";")
    _, blockers, unsupported = live(pg)
    assert blockers, "a direct restore must still stop"
    assert {"kind": kind, "object": obj} in unsupported


def test_identical_check_is_compatible_and_changed_or_added_is_precise(pg):  # noqa: F811
    pg.run(
        "CREATE TABLE visits (id serial PRIMARY KEY, amount numeric(12,2) NOT NULL, "
        "status text, CONSTRAINT visits_amount_positive CHECK (amount >= 0), "
        "CONSTRAINT visits_status CHECK (status in ('new','done')));"
    )
    current, _, _ = live(pg)
    # As Drizzle renders the same declarations in the historical source.
    historical = DataContract.model_validate({"version": 1, "tables": [{
        "name": "visits",
        "columns": [{"name": "id", "type": "integer", "nullable": False},
                    {"name": "amount", "type": "numeric(12,2)", "nullable": False},
                    {"name": "status", "type": "text"}],
        "primary_key": ["id"],
        "check_constraints": [
            {"name": "visits_amount_positive", "definition": '"visits"."amount" >= 0'},
            {"name": "visits_status", "definition": "\"visits\".\"status\" in ('new','done')"},
        ],
    }]})
    assessment = assess_contract(historical, current)
    assert assessment.blockers == []
    assert [d.code for d in assessment.diagnostics if d.code.startswith("check")] == [
        "check_unchanged", "check_unchanged",
    ]
    pg.run(
        "ALTER TABLE visits DROP CONSTRAINT visits_amount_positive; "
        "ALTER TABLE visits ADD CONSTRAINT visits_amount_positive CHECK (amount > 0); "
        "ALTER TABLE visits ADD CONSTRAINT visits_cap CHECK (amount < 1000000);"
    )
    current, _, _ = live(pg)
    assessment = assess_contract(historical, current)
    codes = {(d.code, d.object) for d in assessment.diagnostics}
    assert ("check_changed", "public.visits.visits_amount_positive") in codes
    assert ("check_added", "public.visits.visits_cap") in codes
    assert "check_changed:visits.visits_amount_positive" in assessment.blockers


@pytest.mark.parametrize(
    "expression,ordinary",
    [
        ("'new'::text", True),
        ("'{}'::jsonb", True),
        ("0", True),
        ("(-1)", True),
        ("NULL::character varying", True),
        ("nextval('clients_id_seq'::regclass)", True),
        ("now()", True),
        ("public.mint_code()", False),
        ("lower('X'::text)", False),
        ("(SELECT 1)", False),
    ],
)
def test_ordinary_default_whitelist(expression, ordinary):
    assert ordinary_default(expression) is ordinary


@pytest.mark.parametrize(
    "drizzle,stored",
    [
        ('"v"."amount" >= 0', "CHECK ((amount >= (0)::numeric))"),
        ("\"v\".\"status\" in ('new','done')",
         "CHECK ((status = ANY (ARRAY['new'::text, 'done'::text])))"),
        ('length("v"."name") > 0', "CHECK ((length(name) > 0))"),
        ('"v"."price" > 0.5', "CHECK ((price > 0.5))"),
    ],
)
def test_same_check_in_both_renderings_is_equal(drizzle, stored):
    assert normalize_check(drizzle) == normalize_check(stored)


@pytest.mark.parametrize(
    "left,right",
    [
        ("status = ANY (ARRAY['New'::text,'Done'::text])", "status in ('new','done')"),
        ("((c > 0) AND ((c < 10) OR (c > 100)))", "c > 0 and c < 10 or c > 100"),
        ("x = 'in progress'", "x = 'inprogress'"),
        ("a::integer > 0", "a::text > 0"),
        ("CHECK ((amount >= (0)::numeric))", "amount > 0"),
    ],
)
def test_different_rules_are_never_normalized_equal(left, right):
    # A rendering difference we cannot prove harmless is reported as changed.
    assert normalize_check(left) != normalize_check(right)


def test_oversized_default_or_check_is_an_unsupported_object_not_a_crash(pg):  # noqa: F811
    values = ",".join(f"'v{index:05d}'" for index in range(600))
    pg.run(
        f"CREATE TABLE clients (id serial PRIMARY KEY, status text "
        f"CONSTRAINT clients_status_check CHECK (status IN ({values})), "
        f"note text DEFAULT {chr(39)}{'x' * 2100}{chr(39)});"
    )
    contract, blockers, unsupported = live(pg)
    assert "custom_constraints:clients" in blockers
    assert {"kind": "constraint", "object": "public.clients.clients_status_check"} in unsupported
    assert {"kind": "default", "object": "public.clients.note"} in unsupported
    assert contract.tables[0].check_constraints == []


def test_shadowing_now_function_is_not_an_ordinary_default(pg):  # noqa: F811
    from yleum_orchestrator.services.restoration_catalog import CATALOG_SCRIPT

    pg.run(
        "CREATE FUNCTION public.now() RETURNS timestamptz LANGUAGE sql AS "
        "$$SELECT '2000-01-01'::timestamptz$$; "
        "CREATE TABLE clients (id serial PRIMARY KEY, "
        "at timestamptz DEFAULT public.now());"
    )
    # A role whose search_path puts public first renders it as plain now().
    catalog = json.loads(pg.run("SET search_path = public, pg_catalog;\n" + CATALOG_SCRIPT))
    _, blockers, unsupported = describe_catalog(catalog)
    assert {"kind": "default", "object": "public.clients.at"} in unsupported
    assert blockers == ["custom_column_behavior:clients"]
    pg.run("DROP FUNCTION public.now() CASCADE;")


def test_checks_declared_in_sql_migrations_are_read_in_order():
    from yleum_orchestrator.services.restoration_catalog import migration_checks

    files = {
        "migrations/0001_create_crm_clients.sql": """-- clients
CREATE TABLE IF NOT EXISTS crm_clients (
  id serial PRIMARY KEY,
  status text NOT NULL DEFAULT 'new',
  note text CHECK (char_length(note) <= 500)
);
ALTER TABLE crm_clients
  ADD CONSTRAINT crm_clients_status_check
  CHECK (status IN ('new', 'regular', 'vip', 'inactive'));
""",
        "migrations/0002_visits.sql": """CREATE TABLE crm_client_visits (
  id serial PRIMARY KEY,
  client_id integer NOT NULL REFERENCES crm_clients(id) ON DELETE CASCADE,
  amount numeric(12, 2) NOT NULL CHECK (amount >= 0),
  CONSTRAINT visits_len CHECK (length(note) < 10 AND amount < 100),
  CHECK (amount <> 13)
);
ALTER TABLE crm_clients DROP CONSTRAINT IF EXISTS crm_clients_note_check;
""",
        "src/lib/db/seed.sql": "CREATE TABLE ignored (x int CHECK (x > 0));",
    }
    checks = migration_checks(files)
    assert checks == {
        "crm_clients": [
            {"name": "crm_clients_status_check",
             "definition": "status IN ('new', 'regular', 'vip', 'inactive')"},
        ],
        "crm_client_visits": [
            {"name": "crm_client_visits_amount_check", "definition": "amount >= 0"},
            {"name": "visits_len", "definition": "length(note) < 10 AND amount < 100"},
            {"name": "crm_client_visits_amount_check1", "definition": "amount <> 13"},
        ],
    }


def test_migration_checks_match_the_live_catalog(pg):  # noqa: F811
    from yleum_orchestrator.services.restoration_catalog import migration_checks

    migration = """CREATE TABLE crm_client_visits (
  id serial PRIMARY KEY,
  amount numeric(12, 2) NOT NULL CHECK (amount >= 0),
  status text,
  CHECK (amount <> 13)
);
ALTER TABLE crm_client_visits ADD CONSTRAINT visits_status_check
  CHECK (status IN ('new', 'done'));"""
    pg.run(migration)
    current, _, _ = live(pg)
    declared = migration_checks({"migrations/0001.sql": migration})["crm_client_visits"]
    historical = DataContract.model_validate({"version": 1, "tables": [{
        "name": "crm_client_visits",
        "columns": [{"name": "id", "type": "integer", "nullable": False},
                    {"name": "amount", "type": "numeric(12,2)", "nullable": False},
                    {"name": "status", "type": "text"}],
        "primary_key": ["id"],
        "check_constraints": declared,
    }]})
    assessment = assess_contract(historical, current)
    assert assessment.blockers == []
    assert sorted(d.object for d in assessment.diagnostics if d.code == "check_unchanged") == [
        "public.crm_client_visits.crm_client_visits_amount_check",
        "public.crm_client_visits.crm_client_visits_amount_check1",
        "public.crm_client_visits.visits_status_check",
    ]
