import asyncio
import io
from types import SimpleNamespace
from unittest.mock import AsyncMock, Mock
from uuid import uuid4

import pytest
from PIL import Image

from omnia_api.services import snapshot_preview_capture as capture
from omnia_api.workers.preview import LiveCaptureReport


def png(width):
    output = io.BytesIO()
    Image.new("RGB", (width, 960), color="white").save(output, format="PNG")
    return output.getvalue()


@pytest.fixture
def harness(monkeypatch):
    files = {"src/app/page.tsx": "product"}
    handle = SimpleNamespace(
        refresh_snapshot_files=AsyncMock(side_effect=lambda: dict(files)),
        create_preview_session=AsyncMock(
            return_value=SimpleNamespace(
                preview_url="https://draft.example.com/",
                bootstrap_url="https://draft.example.com/session?token=signed",
            )
        ),
    )
    renderer = AsyncMock(return_value=LiveCaptureReport({390: png(390), 1280: png(1280)}))
    saved = AsyncMock(return_value=True)
    upload = Mock()
    monkeypatch.setattr(capture, "capture_live_url_report", renderer)
    monkeypatch.setattr(capture, "_persist", saved)
    monkeypatch.setattr(capture, "_upload", upload)
    return SimpleNamespace(
        files=files,
        handle=handle,
        renderer=renderer,
        saved=saved,
        upload=upload,
        sid=uuid4(),
        pid=uuid4(),
        sha="a" * 40,
    )


async def run(h):
    return await capture.capture_snapshot_frontend(h.sid, h.pid, h.sha, h.files, h.handle)


async def test_exact_capture_private_manifest(harness):
    h = harness
    assert await run(h)
    assert h.handle.refresh_snapshot_files.await_count == 2
    assert h.renderer.call_args.kwargs["full_page"] is True
    assert h.renderer.call_args.kwargs["bootstrap_url"].endswith("token=signed")
    assert h.renderer.call_args.args[1] == (390, 1280)
    manifest = h.saved.call_args.args[4]
    assert [item["width"] for item in manifest] == [390, 1280]
    assert all(item["height"] == 960 and item["route"] == "/" for item in manifest)
    assert all(item["key"].startswith(f"snapshot-previews/{h.pid}/{h.sid}/") for item in manifest)
    assert h.upload.call_count == 2


@pytest.mark.parametrize("when", ["before", "after"])
async def test_source_mismatch_never_saves_png(harness, when):
    h = harness
    wrong = {**h.files, "src/app/page.tsx": "another generation"}
    h.handle.refresh_snapshot_files.side_effect = [wrong] if when == "before" else [h.files, wrong]
    assert not await run(h)
    h.upload.assert_not_called()
    assert h.saved.call_args.args[3] == "failed"
    if when == "before":
        h.renderer.assert_not_called()


async def test_missing_mobile_capture_fails(harness):
    h = harness
    h.renderer.return_value = LiveCaptureReport({1280: png(1280)})
    assert not await run(h)
    h.upload.assert_not_called()


async def test_generated_type_files_do_not_break_provenance(harness):
    h = harness
    h.handle.refresh_snapshot_files.side_effect = lambda: {
        **h.files,
        "next-env.d.ts": "autogenerated",
        "tsconfig.tsbuildinfo": "cache",
    }
    assert await run(h)


async def test_cancellation_propagates(harness):
    h = harness
    h.renderer.side_effect = asyncio.CancelledError()
    with pytest.raises(asyncio.CancelledError):
        await run(h)
    h.upload.assert_not_called()


async def test_storage_failure_does_not_fail_generation(harness):
    h = harness
    h.upload.side_effect = RuntimeError("storage down")
    assert not await run(h)
    assert h.saved.call_args.args[3] == "failed"


def test_route_chooses_product_avoids_support_dynamic():
    assert (
        capture._main_route(
            {
                "src/app/support/page.tsx": "x",
                "src/app/legal/privacy/page.tsx": "x",
                "src/app/(shop)/catalog/page.tsx": "x",
                "src/app/orders/[id]/page.tsx": "x",
            }
        )
        == "/catalog"
    )


async def test_failed_status_storage_is_fail_soft(harness):
    h = harness
    h.handle.refresh_snapshot_files.side_effect = RuntimeError("Cell gone")
    h.saved.side_effect = RuntimeError("DB unavailable")
    assert not await run(h)


async def test_corrupt_png_not_uploaded(harness):
    h = harness
    h.renderer.return_value = LiveCaptureReport({390: b"not a PNG", 1280: png(1280)})
    assert not await run(h)
    h.upload.assert_not_called()


async def test_no_product_route_does_not_capture_legal_placeholder(harness):
    h = harness
    h.files.clear()
    h.files["src/app/legal/privacy/page.tsx"] = "privacy"
    assert not await run(h)
    h.renderer.assert_not_called()


async def test_upload_uses_private_projects_bucket(monkeypatch):
    client = Mock()
    monkeypatch.setattr(capture, "get_minio_client", lambda: client)
    monkeypatch.setattr(
        capture, "get_settings", lambda: SimpleNamespace(minio_bucket_projects="private-projects")
    )
    capture._upload("snapshot-previews/project/snapshot/digest.png", b"png")
    assert client.put_object.call_args.args[0] == "private-projects"
    client.set_bucket_policy.assert_not_called()


async def test_legacy_max_worker_never_reads_live_source(monkeypatch):
    from omnia_api.workers import preview

    sid, pid = uuid4(), uuid4()
    session = AsyncMock()
    session.get.side_effect = [
        SimpleNamespace(project_id=pid, commit_sha="a" * 40),
        SimpleNamespace(template="max_miniapp"),
    ]
    context = AsyncMock()
    context.__aenter__.return_value = session
    factory = Mock(return_value=context)
    engine = SimpleNamespace(dispose=AsyncMock())
    monkeypatch.setattr(preview, "get_settings", lambda: SimpleNamespace(database_url="test"))
    monkeypatch.setattr(preview, "create_async_engine", lambda *_: engine)
    monkeypatch.setattr(preview, "async_sessionmaker", lambda *_, **__: factory)
    read = Mock()
    monkeypatch.setattr(preview.repo_svc, "read_files", read)
    resolve = AsyncMock()
    monkeypatch.setattr(preview, "_resolve_live_url", resolve)
    await preview._render_async(str(sid))
    read.assert_not_called()
    resolve.assert_not_called()
    engine.dispose.assert_awaited_once()


async def test_cached_source_cannot_substitute_fresh_physical_read(harness):
    h = harness
    h.handle.snapshot_files = AsyncMock(return_value=dict(h.files))
    h.handle.refresh_snapshot_files.return_value = {
        **h.files, "src/app/page.tsx": "changed on disk",
    }
    h.handle.refresh_snapshot_files.side_effect = None
    assert not await run(h)
    h.handle.snapshot_files.assert_not_called()
    h.upload.assert_not_called()


async def test_missing_fresh_source_capability_does_not_save(harness):
    h = harness
    h.handle.refresh_snapshot_files = None
    assert not await run(h)
    h.renderer.assert_not_called()
    h.upload.assert_not_called()
