apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
kubeReserved:
  cpu: 500m
  memory: 1Gi
  ephemeral-storage: 2Gi
  pid: "1000"
systemReserved:
  cpu: 1500m
  memory: 4Gi
  ephemeral-storage: 10Gi
  pid: "4096"
evictionHard:
  memory.available: 1Gi
  nodefs.available: 15%
  nodefs.inodesFree: 10%
  imagefs.available: 15%
  pid.available: 10%
enforceNodeAllocatable:
  - pods
podPidsLimit: 4096
