#!/usr/bin/env bash
# 05-acme-dns.sh — свой acme-dns на core: DNS-01 для wildcard-сертификатов БЕЗ API reg.ru.
#
# Идея (владелец: «API не нужен для начала»): в зоне yleum.ru один раз делегируется поддомен
# acme.yleum.ru на наш сервер, а имена _acme-challenge.<база> ведут CNAME'ом на запись внутри него.
# Дальше Let's Encrypt спрашивает TXT у нас, а acme.sh (hook dns_acmedns) пишет его через локальный
# HTTP API — продление полностью автоматическое, доступ к DNS-панели не нужен.
#
# Запуск на core от root:
#   05-acme-dns.sh install   — контейнер joohoi/acme-dns (порт 53 только на публичном IP, API на 127.0.0.1:8053),
#                              ufw, регистрация одного аккаунта (креды в /etc/max-studio/edge/acme-dns.env),
#                              затем регистрация закрывается; печатает записи для владельца
#   05-acme-dns.sh records   — ещё раз напечатать записи для DNS-панели
#   05-acme-dns.sh test      — записать пробный TXT через API и прочитать его по DNS с публичного IP
#   05-acme-dns.sh check     — проверить, что делегирование в yleum.ru уже сделано (NS + CNAME'ы видны снаружи)
#   05-acme-dns.sh status
# Идемпотентен. Ничего не удаляет; откат — `docker rm -f omnia-acme-dns` и удаление записей в панели.
set -euo pipefail
STEP=${1:-status}
EDGE_DOMAIN=${EDGE_DOMAIN:-yleum.ru}
ACME_ZONE=${ACME_ZONE:-acme.$EDGE_DOMAIN}
NS_NAME=${NS_NAME:-ns-acme.$EDGE_DOMAIN}
PUBLIC_IP=${PUBLIC_IP:-2.153.248.98}
# Serverum транслирует публичный IP на внутренний адрес интерфейса по умолчанию (1:1 NAT): пакеты на :53
# приходят с dst = этот адрес, а не публичный. Слушаем на обоих (публичный висит на lo — для локальных проверок).
NAT_IP=${NAT_IP:-$(ip -4 route get 1.1.1.1 2>/dev/null | sed -n 's/.* src \([0-9.]*\).*/\1/p' | head -1)}
API_BIND=${API_BIND:-127.0.0.1:8053}
BASES=${BASES:-"$EDGE_DOMAIN apps.$EDGE_DOMAIN dev.$EDGE_DOMAIN dev2.$EDGE_DOMAIN"}
IMAGE=${ACME_DNS_IMAGE:-joohoi/acme-dns:latest}
NAME=omnia-acme-dns
CONF_DIR=/etc/max-studio/acme-dns
DATA_DIR=/var/lib/omnia-acme-dns
EDGE_DIR=/etc/max-studio/edge
CREDS="$EDGE_DIR/acme-dns.env"
log() { printf '\n\033[1;34m[%s] %s\033[0m\n' "$(date +%H:%M:%S)" "$*"; }
die() { printf '\033[1;31mОШИБКА: %s\033[0m\n' "$*" >&2; exit 1; }
[ "$(id -u)" = 0 ] || die "запускать от root (sudo)"

write_config() { # write_config <disable_registration true|false>
  install -d -m 700 "$CONF_DIR" "$DATA_DIR" "$EDGE_DIR"
  cat > "$CONF_DIR/config.cfg" <<EOF
[general]
listen = "0.0.0.0:53"
protocol = "both"
domain = "$ACME_ZONE"
nsname = "$NS_NAME"
nsadmin = "admin.$EDGE_DOMAIN"
records = [
    "$ACME_ZONE. A $PUBLIC_IP",
    "$NS_NAME. A $PUBLIC_IP",
    "$ACME_ZONE. NS $NS_NAME.",
]
debug = false

[database]
engine = "sqlite"
connection = "/var/lib/acme-dns/acme-dns.db"

[api]
ip = "0.0.0.0"
disable_registration = $1
port = "80"
tls = "none"
corsorigins = []
use_header = false
header_name = "X-Forwarded-For"

[logconfig]
loglevel = "info"
logtype = "stdout"
logformat = "text"
EOF
  chmod 600 "$CONF_DIR/config.cfg"
}

run_container() {
  docker rm -f "$NAME" >/dev/null 2>&1 || true
  # Порт 53 только на публичном адресе (он висит на lo): 127.0.0.53/54 остаются у systemd-resolved.
  local ports=(-p "$PUBLIC_IP:53:53/udp" -p "$PUBLIC_IP:53:53/tcp")
  [ -n "$NAT_IP" ] && [ "$NAT_IP" != "$PUBLIC_IP" ] && ports+=(-p "$NAT_IP:53:53/udp" -p "$NAT_IP:53:53/tcp")
  docker run -d --name "$NAME" --restart unless-stopped \
    "${ports[@]}" -p "$API_BIND:80" \
    -v "$CONF_DIR/config.cfg:/etc/acme-dns/config.cfg:ro" -v "$DATA_DIR:/var/lib/acme-dns" \
    --memory 128m --pids-limit 64 --security-opt no-new-privileges:true \
    "$IMAGE" >/dev/null
  for _ in $(seq 1 20); do curl -fsS -m 2 "http://$API_BIND/health" >/dev/null 2>&1 && break; sleep 1; done
  curl -fsS -m 2 "http://$API_BIND/health" >/dev/null || { docker logs --tail 20 "$NAME"; die "acme-dns не поднялся"; }
}

print_records() {
  # shellcheck disable=SC1090
  . "$CREDS"
  cat <<EOF

Записи для DNS-панели зоны $EDGE_DOMAIN (один раз):
  $NS_NAME.                A      $PUBLIC_IP
  $ACME_ZONE.              NS     $NS_NAME.
EOF
  for b in $BASES; do printf '  _acme-challenge.%-24s CNAME  %s.\n' "$b." "$ACMEDNS_FULLDOMAIN"; done
  echo
}

case "$STEP" in
  install)
    log "образ и контейнер acme-dns"
    docker pull -q "$IMAGE" >/dev/null
    if [ -f "$CREDS" ]; then
      write_config true; run_container
      log "аккаунт уже зарегистрирован ($CREDS) — регистрация закрыта"
    else
      write_config false; run_container
      log "регистрация единственного аккаунта acme-dns"
      reg=$(curl -fsS -m 5 -X POST "http://$API_BIND/register") || die "регистрация не удалась"
      umask 077
      python3 - "$reg" > "$CREDS" <<'PY'
import json, sys
r = json.loads(sys.argv[1])
print("# acme-dns account for acme.sh (dns_acmedns); generated by 05-acme-dns.sh")
print(f"ACMEDNS_BASE_URL=http://127.0.0.1:8053")
print(f"ACMEDNS_USERNAME={r['username']}")
print(f"ACMEDNS_PASSWORD={r['password']}")
print(f"ACMEDNS_SUBDOMAIN={r['subdomain']}")
print(f"ACMEDNS_FULLDOMAIN={r['fulldomain']}")
PY
      chmod 600 "$CREDS"
      write_config true; run_container
      log "регистрация закрыта (disable_registration = true), креды в $CREDS (0600)"
    fi
    log "ufw: 53/udp и 53/tcp на $PUBLIC_IP для всех (валидаторы Let's Encrypt спрашивают наш NS напрямую)"
    for ip in $PUBLIC_IP $NAT_IP; do
      ufw allow to "$ip" port 53 proto udp comment 'acme-dns (DNS-01 for wildcard certs)' >/dev/null
      ufw allow to "$ip" port 53 proto tcp comment 'acme-dns (DNS-01 for wildcard certs)' >/dev/null
    done
    ufw reload >/dev/null
    "$0" test
    print_records
    ;;
  records) [ -f "$CREDS" ] || die "сначала install"; print_records ;;
  test)
    [ -f "$CREDS" ] || die "сначала install"
    # shellcheck disable=SC1090
    . "$CREDS"
    val="probe-$(date +%s)-0000000000000000000000000000000"; val=${val:0:43}
    curl -fsS -m 5 -X POST "http://$API_BIND/update" -H "X-Api-User: $ACMEDNS_USERNAME" -H "X-Api-Key: $ACMEDNS_PASSWORD" \
      -d "{\"subdomain\":\"$ACMEDNS_SUBDOMAIN\",\"txt\":\"$val\"}" >/dev/null || die "API /update не принял TXT"
    got=$(dig +short +time=3 +tries=1 "@$PUBLIC_IP" "$ACMEDNS_FULLDOMAIN" TXT | tr -d '"')
    grep -q "$val" <<<"$got" || die "DNS на $PUBLIC_IP:53 не отдал пробный TXT (получено: $got)"
    soa=$(dig +short +time=3 +tries=1 "@$PUBLIC_IP" "$ACME_ZONE" SOA | awk '{print $1}')
    echo "TEST_OK: TXT $ACMEDNS_FULLDOMAIN отдаётся с $PUBLIC_IP:53, SOA $ACME_ZONE → $soa"
    ;;
  check)
    [ -f "$CREDS" ] || die "сначала install"
    # shellcheck disable=SC1090
    . "$CREDS"
    ok=1
    ns=$(dig +short +time=5 "$ACME_ZONE" NS @1.1.1.1 | tr -d '\n')
    if [ "$ns" = "$NS_NAME." ]; then echo "NS $ACME_ZONE → $ns  ок"; else echo "NS $ACME_ZONE: получено '$ns', ожидается $NS_NAME."; ok=0; fi
    a=$(dig +short +time=5 "$NS_NAME" A @1.1.1.1)
    if [ "$a" = "$PUBLIC_IP" ]; then echo "A $NS_NAME → $a  ок"; else echo "A $NS_NAME: получено '$a', ожидается $PUBLIC_IP"; ok=0; fi
    for b in $BASES; do
      c=$(dig +short +time=5 "_acme-challenge.$b" CNAME @1.1.1.1)
      if [ "$c" = "$ACMEDNS_FULLDOMAIN." ]; then echo "CNAME _acme-challenge.$b → $c  ок"; else echo "CNAME _acme-challenge.$b: получено '$c', ожидается $ACMEDNS_FULLDOMAIN."; ok=0; fi
    done
    txt=$(dig +short +time=5 "_acme-challenge.$EDGE_DOMAIN" TXT @1.1.1.1 | head -1)
    echo "TXT через делегирование (_acme-challenge.$EDGE_DOMAIN, публичный резолвер): ${txt:-пусто}"
    [ "$ok" = 1 ] && echo "CHECK_OK: делегирование на месте — можно выпускать" || { echo "CHECK_PENDING: записи ещё не видны (TTL/распространение) или не добавлены"; exit 2; }
    ;;
  status)
    docker ps --filter "name=$NAME" --format '{{.Names}} {{.Status}} {{.Ports}}' || true
    [ -f "$CREDS" ] && { . "$CREDS"; echo "аккаунт: $ACMEDNS_FULLDOMAIN"; } || echo "аккаунт не зарегистрирован"
    ;;
  *) die "неизвестный шаг: $STEP" ;;
esac
