#!/usr/bin/env bash
# Edge (Фаза 1): единый wildcard-сертификат для всех трёх хостов. Драйвер, запускается с Mac (bash 3.2 ok):
#
#   ./edge.sh install            скрипты на хосты (/usr/local/sbin/max-edge-*), edge.env, таймер продления на core
#   ./edge.sh creds              REGRU_API_Username / REGRU_API_Password из окружения Mac → core:/etc/max-studio/edge/regru.env
#   ./edge.sh authorize          ключ раздачи core → runtime и commerce (пользователь maxedge, только «receive <роль>»)
#   ./edge.sh issue              выпуск через DNS-01 reg.ru на core + установка + раздача на все хосты
#   ./edge.sh distribute         повторная раздача текущего сертификата (idempotent)
#   ./edge.sh orchestrator-env on|off   OMNIA_WILDCARD_CERT_ROOT в .env оркестратора на core и commerce
#   ./edge.sh k8s-mode wildcard|cert-manager   K8S_TLS_MODE в .env оркестратора на core (с проверкой секрета в runtime)
#   ./edge.sh status             срок действия на core + что отдают публичные адреса (openssl s_client с Mac)
#   ./edge.sh rollback           все хосты обратно: certbot/самоподписанный/без TLSStore (см. README, раздел Edge)
#   ./edge.sh all                install → creds → authorize → issue → orchestrator-env on → status
#
# Секреты reg.ru нигде не печатаются и не попадают в argv: только stdin → файл 0600 на core.
set -euo pipefail
. "$(dirname "$0")/../lib.sh"
E="$HERE/edge"
EDGE_DIR=/etc/max-studio/edge
ORCH_ENV=/opt/omnia/apps/orchestrator/.env
ACME_EMAIL=${ACME_EMAIL:-admin@$DOMAIN}

# upload <host> <local file> <remote path> [mode]
upload() {
  local h=$1 src=$2 dst=$3 mode=${4:-0755}
  ssh -o BatchMode=yes "$(inv "$h" alias)" "sudo bash -c 'umask 022; cat > $dst.new && chmod $mode $dst.new && mv -f $dst.new $dst'" < "$src"
}

# set_env <host> <file> <key> <value|-> — обновить/добавить ключ; '-' удаляет
set_env() {
  local h=$1 f=$2 k=$3 v=$4
  if [ "$v" = "-" ]; then
    sh_remote "$h" "[ -f $f ] && sed -i '/^$k=/d' $f || true"
  else
    sh_remote "$h" "touch $f; if grep -q '^$k=' $f; then sed -i 's#^$k=.*#$k=$v#' $f; else printf '%s=%s\n' '$k' '$v' >> $f; fi"
  fi
}

phase_install() {
  local peers="" h
  for h in $HOSTS; do [ "$h" = core ] || peers="$peers $h:$(inv "$h" wg)"; done
  for h in $HOSTS; do
    log "install → $h"
    upload "$h" "$E/20-wildcard-distribute.sh" /usr/local/sbin/max-edge-distribute
    sh_remote "$h" "install -d -m 700 $EDGE_DIR; umask 077; cat > $EDGE_DIR/edge.env <<EOF
# generated by infra/max-k3s/edge/edge.sh install
EDGE_DOMAIN=$DOMAIN
EDGE_PEERS=\"${peers# }\"
EDGE_ACME_EMAIL=$ACME_EMAIL
EOF"
  done
  upload core "$E/10-wildcard-issue.sh" /usr/local/sbin/max-edge-issue
  sh_remote core "/usr/local/sbin/max-edge-issue timer"
}

phase_creds() {
  local u=${REGRU_API_Username:-} p=${REGRU_API_Password:-}
  if [ -z "$u" ] || [ -z "$p" ]; then
    if [ -t 0 ]; then
      read -r -p "reg.ru API username: " u
      read -r -s -p "reg.ru API password (не печатается): " p; echo
    else
      echo "creds: задайте REGRU_API_Username и REGRU_API_Password в окружении" >&2; exit 1
    fi
  fi
  printf 'REGRU_API_Username=%s\nREGRU_API_Password=%s\n' "$u" "$p" \
    | ssh -o BatchMode=yes "$(inv core alias)" "sudo bash -c 'umask 077; install -d -m 700 $EDGE_DIR; cat > $EDGE_DIR/regru.env; chmod 600 $EDGE_DIR/regru.env'"
  log "creds: core:$EDGE_DIR/regru.env записан (0600, root)"
}

phase_authorize() {
  local pub h
  pub=$(sh_remote core "/usr/local/sbin/max-edge-distribute keygen" | tail -1)
  [ -n "$pub" ] || { echo "authorize: не получил публичный ключ с core" >&2; exit 1; }
  for h in $HOSTS; do
    [ "$h" = core ] && continue
    log "authorize → $h"
    sh_remote "$h" "/usr/local/sbin/max-edge-distribute authorize '$pub' $h"
  done
}

phase_issue() { log "issue → core (DNS-01 reg.ru)"; sh_remote core "/usr/local/sbin/max-edge-issue issue"; }
phase_distribute() { log "distribute → core push"; sh_remote core "/usr/local/sbin/max-edge-distribute push"; }

phase_orchestrator_env() {
  local mode=${1:-on} h
  for h in core commerce; do
    if [ "$mode" = on ]; then
      set_env "$h" "$ORCH_ENV" OMNIA_WILDCARD_CERT_ROOT "$EDGE_DIR/wildcard"
    else
      set_env "$h" "$ORCH_ENV" OMNIA_WILDCARD_CERT_ROOT -
    fi
    log "orchestrator-env $mode → $h: $(sh_remote "$h" "grep '^OMNIA_WILDCARD_CERT_ROOT=' $ORCH_ENV || echo 'OMNIA_WILDCARD_CERT_ROOT снят'")"
  done
  echo "  перезапуск оркестратора — вручную, когда нет активных генераций: ssh max-<host> sudo systemctl restart omnia-orchestrator"
}

phase_k8s_mode() {
  local mode=${1:-}
  case "$mode" in
    wildcard)
      sh_remote core "k3s kubectl --kubeconfig /etc/max-studio/runtime-kubeconfig.yaml -n kube-system get secret wildcard-yleum -o name" >/dev/null \
        || { echo "k8s-mode: в runtime нет Secret kube-system/wildcard-yleum — сначала ./edge.sh issue или distribute" >&2; exit 1; }
      ;;
    cert-manager) ;;
    *) echo "k8s-mode wildcard|cert-manager" >&2; exit 1 ;;
  esac
  set_env core "$ORCH_ENV" K8S_TLS_MODE "$mode"
  log "k8s-mode → core: $(sh_remote core "grep '^K8S_TLS_MODE=' $ORCH_ENV")"
  echo "  вступает в силу после перезапуска оркестратора на core (когда нет активных публикаций)"
}

probe() {
  local ip=$1 sni=$2 sans
  sans=$(echo | openssl s_client -connect "$ip:443" -servername "$sni" 2>/dev/null \
    | openssl x509 -noout -ext subjectAltName 2>/dev/null | tr ',' '\n' | sed -n 's/^ *DNS://p' | tr '\n' ' ' || true)
  printf '  %-34s %-15s %s\n' "$sni" "$ip" "${sans:-(нет ответа / не TLS)}"
}

phase_status() {
  log "status: сертификат на core"
  sh_remote core "/usr/local/sbin/max-edge-issue status" || true
  for h in $HOSTS; do sh_remote "$h" "/usr/local/sbin/max-edge-distribute status $h" || true; done
  log "status: что отдают публичные адреса (SAN сертификата на :443)"
  probe "$(inv core public)" "$DOMAIN"
  probe "$(inv core public)" "grafana.$DOMAIN"
  probe "$(inv runtime public)" "edge-probe.apps.$DOMAIN"
  probe "$(inv core public)" "edge-probe.dev.$DOMAIN"
  probe "$(inv commerce public)" "edge-probe.dev2.$DOMAIN"
  echo "  (*.dev/*.dev2 без живого превью отдают catch-all с самоподписанным сертификатом — так и задумано;"
  echo "   wildcard там подставляется оркестратором в vhost каждого превью)"
}

phase_rollback() {
  local h
  phase_orchestrator_env off
  for h in $HOSTS; do log "rollback → $h"; sh_remote "$h" "/usr/local/sbin/max-edge-distribute rollback $h" || true; done
  phase_k8s_mode cert-manager
  sh_remote core "systemctl disable --now max-edge-renew.timer >/dev/null 2>&1 || true"
  echo "  дальше: перезапустить оркестраторы (core, commerce); приложения, опубликованные в режиме wildcard, уже переведены на cert-manager на уровне Ingress"
}

case "${1:-}" in
  install|creds|authorize|issue|distribute|status|rollback) "phase_$1" ;;
  orchestrator-env) phase_orchestrator_env "${2:-on}" ;;
  k8s-mode) phase_k8s_mode "${2:-}" ;;
  all) phase_install; phase_creds; phase_authorize; phase_issue; phase_orchestrator_env on; phase_status ;;
  *) sed -n '2,14p' "$0"; exit 1 ;;
esac
