"""Render the Omnia-managed MAX application kit without calling a model."""

# ruff: noqa: E501

from __future__ import annotations

import json
import re
from pathlib import Path
from uuid import UUID

from omnia_api.schemas.max_studio import MaxProjectConfigPayload

# Increment whenever the managed file set changes in a way that existing MAX
# projects must receive. It deliberately does not follow the public config
# schema version: this is a deployment revision of platform-owned source files.
MAX_MANAGED_KIT_VERSION = 10
_MANAGED_COMPONENT_IMPORT_RE = re.compile(r"""from\s+["']@/components/(Omnia[A-Za-z0-9_/-]+)["']""")


def _template_candidates(
    relative_path: str,
    source_file: Path | None = None,
) -> tuple[Path, ...]:
    source = (source_file or Path(__file__)).resolve()
    return (
        Path("/orchestrator/templates/max-miniapp-nextjs") / relative_path,
        *(
            parent / "apps" / "orchestrator" / "templates" / "max-miniapp-nextjs" / relative_path
            for parent in source.parents
        ),
    )


def _template_file(relative_path: str) -> str:
    """Read one platform-owned MAX template file from dev or the API mount."""
    for candidate in _template_candidates(relative_path):
        if candidate.is_file():
            return candidate.read_text(encoding="utf-8")
    raise RuntimeError(f"MAX managed template file is unavailable: {relative_path}")


def _json(config: MaxProjectConfigPayload) -> str:
    return json.dumps(
        config.model_dump(mode="json", exclude={"max_url_attached"}),
        ensure_ascii=False,
        indent=2,
        separators=(",", ": "),
    )


_CONFIG_TYPES = """export type OmniaMaxContentItem = {
  id: string;
  title: string;
  description: string;
  price: string;
  action_label: string;
  active: boolean;
};

export type OmniaMaxConfig = {
  app_name: string;
  app_type: "loyalty" | "catalog" | "booking" | "event" | "education" | "custom";
  summary: string;
  audience: string;
  primary_action: string;
  features: string[];
  style: "brand" | "clean" | "bright";
  brand_colors: string;
  content: OmniaMaxContentItem[];
  operator: { legal_name: string; inn: string; ogrn: string; address: string };
  support: { email: string | null; phone: string; response_time: string };
  legal: {
    age_rating: "0+" | "6+" | "12+" | "16+" | "18+";
    has_sales: boolean;
    has_user_content: boolean;
    marketing_notifications: boolean;
    personal_data_consent: boolean;
    terms_accepted: boolean;
  };
};
"""


def _validate_managed_component_graph(files: dict[str, str]) -> None:
    """Refuse an incomplete platform kit before it reaches a project snapshot.

    Omnia-prefixed components are owned by the platform, so every such import
    must travel in the same atomic managed-file set. This keeps a future kit
    edit from turning a valid user app into a runtime `Module not found` error.
    """
    required = {
        f"src/components/{component}.tsx"
        for content in files.values()
        for component in _MANAGED_COMPONENT_IMPORT_RE.findall(content)
    }
    missing = sorted(required.difference(files))
    if missing:
        raise RuntimeError(f"MAX managed kit is missing imported files: {', '.join(missing)}")


def render_max_managed_files(
    config: MaxProjectConfigPayload, project_id: UUID | str | None = None
) -> dict[str, str]:
    """Files safe to apply to both a starter and an already-generated app."""
    data = _json(config)
    project_literal = json.dumps(str(project_id) if project_id else "")
    preview_session_route = _template_file("src/app/api/omnia/preview-session/route.ts").replace(
        '"__OMNIA_PROJECT_ID__"', project_literal, 1
    )
    files = {
        "src/components/MaxAppProvider.tsx": _template_file("src/components/MaxAppProvider.tsx"),
        "src/components/OmniaCompliance.tsx": _template_file("src/components/OmniaCompliance.tsx"),
        "src/lib/max/validate-init-data.ts": _template_file("src/lib/max/validate-init-data.ts"),
        "src/app/api/max/session/route.ts": _template_file("src/app/api/max/session/route.ts"),
        "src/lib/max/session.ts": _template_file("src/lib/max/session.ts"),
        "src/app/api/omnia/preview-session/route.ts": preview_session_route,
        "src/lib/omnia/max-config.ts": (
            "/* Generated by MAX Studio. Edit the business profile in Omnia, not this file. */\n"
            f"{_CONFIG_TYPES}\n"
            f"export const omniaMaxConfig: OmniaMaxConfig = {data};\n"
        ),
        "src/app/api/omnia/config/route.ts": """import { NextResponse } from "next/server";

import { omniaMaxConfig } from "@/lib/omnia/max-config";

export const dynamic = "force-static";

export function GET() {
  return NextResponse.json(omniaMaxConfig, {
    headers: { "Cache-Control": "public, max-age=60, stale-while-revalidate=300" },
  });
}
""",
        "src/lib/omnia/integration-client.ts": """\"use client\";

import { getMaxWebApp } from "@/lib/max/bridge";

async function invoke<T>(
  path: "status" | "payments" | "payment-status" | "leads" | "catalog",
  payload: Record<string, unknown> = {},
): Promise<T> {
  const initData = getMaxWebApp()?.initData;
  if (!initData) throw new Error("Откройте приложение внутри MAX");
  const response = await fetch(`/api/omnia/integrations/${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ initData, payload }),
  });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) {
    throw new Error(body?.error?.message || "Интеграция временно недоступна");
  }
  return body as T;
}

export type OmniaIntegrationStatus = {
  providers: string[];
  capabilities: string[];
  analytics_counter_id: string | null;
};

export function getOmniaIntegrations(): Promise<OmniaIntegrationStatus> {
  return invoke("status");
}

export function createOmniaPayment(input: {
  amount: number;
  description: string;
  return_url: string;
  idempotency_key?: string;
  metadata?: Record<string, string>;
  receipt?: Record<string, unknown>;
}): Promise<{ id: string; status: string; confirmation_url: string | null }> {
  return invoke("payments", {
    ...input,
    idempotency_key: input.idempotency_key || crypto.randomUUID(),
  });
}

export function getOmniaPayment(paymentId: string): Promise<{
  id: string;
  status: string;
  confirmation_url: string | null;
}> {
  return invoke("payment-status", { payment_id: paymentId });
}

export function createOmniaLead(input: {
  name: string;
  phone?: string;
  email?: string;
  comment?: string;
  source?: string;
}): Promise<{ provider: string; id: string }> {
  return invoke("leads", input);
}

export function getOmniaCatalog(): Promise<{
  provider: string;
  items: Array<{
    id: string;
    name: string;
    description: string;
    price: number | null;
    currency: string;
    available: boolean;
    image_url: string | null;
  }>;
}> {
  return invoke("catalog");
}

export async function trackOmniaGoal(
  goal: string,
  parameters: Record<string, unknown> = {},
): Promise<void> {
  const status = await getOmniaIntegrations();
  const counterId = status.analytics_counter_id;
  if (!counterId || typeof window === "undefined") return;
  const target = window as typeof window & { ym?: (...args: unknown[]) => void };
  if (!target.ym) {
    target.ym = (...args: unknown[]) => {
      (target.ym as unknown as { a?: unknown[] }).a =
        (target.ym as unknown as { a?: unknown[] }).a || [];
      (target.ym as unknown as { a: unknown[] }).a.push(args);
    };
    const script = document.createElement("script");
    script.async = true;
    script.src = "https://mc.yandex.ru/metrika/tag.js";
    document.head.appendChild(script);
    target.ym(Number(counterId), "init", {
      clickmap: true,
      trackLinks: true,
      accurateTrackBounce: true,
    });
  }
  target.ym(Number(counterId), "reachGoal", goal, parameters);
}
""",
        "src/app/api/omnia/integrations/[...path]/route.ts": f"""import {{ NextRequest, NextResponse }} from "next/server";

const PROJECT_ID = {project_literal};
const PLATFORM_API = (
  process.env.OMNIA_PLATFORM_API_URL || "https://constructor.lead-generator.ru"
).replace(/\\/$/, "");

type Context = {{ params: Promise<{{ path: string[] }}> }};

export async function POST(request: NextRequest, context: Context) {{
  if (!PROJECT_ID) {{
    return NextResponse.json(
      {{ error: {{ message: "Integration Hub ещё не синхронизирован с приложением" }} }},
      {{ status: 503 }},
    );
  }}
  const {{ path }} = await context.params;
  const operation = path.join("/");
  if (!["status", "payments", "payment-status", "leads", "catalog"].includes(operation)) {{
    return NextResponse.json({{ error: {{ message: "Unknown capability" }} }}, {{ status: 404 }});
  }}
  const body = await request.json().catch(() => ({{}})) as {{
    initData?: unknown;
    payload?: unknown;
  }};
  if (typeof body.initData !== "string") {{
    return NextResponse.json(
      {{ error: {{ message: "Откройте приложение внутри MAX" }} }},
      {{ status: 401 }},
    );
  }}
  const readOnly = operation === "status" || operation === "catalog";
  const upstreamPath =
    operation === "status"
      ? `/api/runtime/projects/${{PROJECT_ID}}/integrations`
      : operation === "catalog"
        ? `/api/runtime/projects/${{PROJECT_ID}}/catalog`
      : operation === "payment-status"
        ? `/api/runtime/projects/${{PROJECT_ID}}/payments/status`
        : `/api/runtime/projects/${{PROJECT_ID}}/${{operation}}`;
  const upstream = await fetch(`${{PLATFORM_API}}${{upstreamPath}}`, {{
    method: readOnly ? "GET" : "POST",
    headers: {{
      "Content-Type": "application/json",
      "X-MAX-Init-Data": body.initData,
    }},
    body: readOnly ? undefined : JSON.stringify(body.payload || {{}}),
    cache: "no-store",
  }});
  const responseBody = await upstream.text();
  return new NextResponse(responseBody, {{
    status: upstream.status,
    headers: {{ "Content-Type": upstream.headers.get("content-type") || "application/json" }},
  }});
}}
""",
        "src/app/legal/privacy/page.tsx": """import { omniaMaxConfig as app } from "@/lib/omnia/max-config";

export const metadata = { title: `Политика конфиденциальности — ${app.app_name}` };

export default function PrivacyPage() {
  const operator = app.operator.legal_name || app.app_name;
  return (
    <main style={{ maxWidth: 760, margin: "0 auto", padding: "32px 20px 64px", lineHeight: 1.65 }}>
      <h1>Политика конфиденциальности</h1>
      <p><strong>Оператор:</strong> {operator}</p>
      {app.operator.inn && <p><strong>ИНН:</strong> {app.operator.inn}</p>}
      {app.operator.address && <p><strong>Адрес:</strong> {app.operator.address}</p>}
      <h2>Какие данные обрабатываются</h2>
      <p>
        Приложение получает от MAX идентификатор пользователя и доступные данные профиля,
        необходимые для входа и работы функций приложения. Действия, заказы, записи и
        обращения сохраняются только в объёме, необходимом для оказания услуги.
      </p>
      <h2>Цели и срок обработки</h2>
      <p>
        Данные используются для исполнения запросов пользователя, поддержки, безопасности
        и улучшения сервиса. Они хранятся не дольше, чем требуют эти цели и закон.
      </p>
      <h2>Права пользователя</h2>
      <p>
        Пользователь может запросить сведения, исправление или удаление данных через
        страницу поддержки. Согласие на необязательные уведомления можно отозвать.
      </p>
      <p>Возрастная маркировка: {app.legal.age_rating}.</p>
      <p>Дата актуализации: {new Date().toLocaleDateString("ru-RU")}.</p>
    </main>
  );
}
""",
        "src/app/legal/terms/page.tsx": """import { omniaMaxConfig as app } from "@/lib/omnia/max-config";

export const metadata = { title: `Условия использования — ${app.app_name}` };

export default function TermsPage() {
  const operator = app.operator.legal_name || app.app_name;
  return (
    <main style={{ maxWidth: 760, margin: "0 auto", padding: "32px 20px 64px", lineHeight: 1.65 }}>
      <h1>Условия использования</h1>
      <p>
        Эти условия регулируют использование мини-приложения «{app.app_name}».
        Владелец сервиса: {operator}.
      </p>
      <h2>Возможности сервиса</h2>
      <p>{app.summary}</p>
      <h2>Правила</h2>
      <p>
        Нельзя нарушать закон, права других лиц, пытаться получить чужие данные,
        вмешиваться в работу сервиса или использовать его для спама и обмана.
      </p>
      {app.legal.has_sales && (
        <>
          <h2>Заказы и оплата</h2>
          <p>
            Итоговая цена, состав заказа, способ оплаты, отмены и возврата показываются
            до подтверждения. Платёж обрабатывает указанный при оформлении провайдер.
          </p>
        </>
      )}
      {app.legal.has_user_content && (
        <>
          <h2>Пользовательский контент</h2>
          <p>
            Запрещён незаконный и оскорбительный контент. Владелец вправе ограничить
            доступ и удалить нарушение; жалобу можно отправить через поддержку.
          </p>
        </>
      )}
      <p>Возрастная маркировка: {app.legal.age_rating}.</p>
    </main>
  );
}
""",
        "src/app/support/page.tsx": """import { omniaMaxConfig as app } from "@/lib/omnia/max-config";

export const metadata = { title: `Поддержка — ${app.app_name}` };

export default function SupportPage() {
  return (
    <main style={{ maxWidth: 680, margin: "0 auto", padding: "32px 20px 64px", lineHeight: 1.65 }}>
      <h1>Поддержка</h1>
      <p>Опишите проблему, ожидаемый результат и время, когда она возникла.</p>
      {app.support.email && <p><strong>Email:</strong> <a href={`mailto:${app.support.email}`}>{app.support.email}</a></p>}
      {app.support.phone && <p><strong>Телефон:</strong> <a href={`tel:${app.support.phone}`}>{app.support.phone}</a></p>}
      <p>{app.support.response_time}</p>
      <nav style={{ display: "flex", gap: 16, flexWrap: "wrap", marginTop: 28 }}>
        <a href="/legal/privacy">Конфиденциальность</a>
        <a href="/legal/terms">Условия использования</a>
      </nav>
    </main>
  );
}
""",
    }
    _validate_managed_component_graph(files)
    return files


MAX_MODEL_LOCKED_FILES = frozenset(
    {
        "src/components/MaxAppProvider.tsx",
        "src/components/OmniaCompliance.tsx",
        "src/app/layout.tsx",
        "src/lib/max/validate-init-data.ts",
        "src/app/api/max/session/route.ts",
        "src/lib/max/session.ts",
        "src/app/api/omnia/preview-session/route.ts",
        "src/lib/omnia/max-config.ts",
        "src/app/api/omnia/config/route.ts",
        "src/lib/omnia/integration-client.ts",
        "src/app/api/omnia/integrations/[...path]/route.ts",
        "src/app/legal/privacy/page.tsx",
        "src/app/legal/terms/page.tsx",
        "src/app/support/page.tsx",
    }
)

MAX_MODEL_DIRECTIVE = """
MAX TEMPLATE CONTRACT
The application is already complete and buildable from the deterministic MAX
template. Preserve the MAX bridge, authenticated session, legal/support routes,
integration client and generated business config. Do not rewrite platform-owned
files. For a user edit, inspect only the relevant screen/component and change the
smallest necessary file set; prefer src/app/page.tsx and src/app/globals.css.
Create another route/component only when the requested behaviour truly requires it.
The bash tool is disabled for MAX: all source changes must use edit_file/write_file
so Omnia can attribute and safely roll them back.
""".strip()


def render_max_starter_files(
    config: MaxProjectConfigPayload, project_id: UUID | str | None = None
) -> dict[str, str]:
    """Complete, buildable MAX app assembled without a model.

    The dynamic home screen reads the business config, so loyalty, catalog,
    booking, event and education projects all start as a personalised working
    application. A model is reserved for later, genuinely custom edits.
    """
    return {
        **render_max_managed_files(config, project_id),
        "src/app/page.tsx": _template_file("src/app/page.tsx"),
        "src/app/globals.css": _template_file("src/app/globals.css"),
        "src/app/layout.tsx": _template_file("src/app/layout.tsx"),
    }
