"""Render the Omnia-managed MAX application kit without calling a model."""

# ruff: noqa: E501

from __future__ import annotations

import json

from omnia_api.schemas.max_studio import MaxProjectConfigPayload


def _json(config: MaxProjectConfigPayload) -> str:
    return json.dumps(
        config.model_dump(mode="json", exclude={"max_url_attached"}),
        ensure_ascii=False,
        indent=2,
        separators=(",", ": "),
    )


def render_max_managed_files(config: MaxProjectConfigPayload) -> dict[str, str]:
    """Files safe to apply to both a starter and an already-generated app."""
    data = _json(config)
    return {
        "src/lib/omnia/max-config.ts": (
            "/* Generated by MAX Studio. Edit the business profile in Omnia, not this file. */\n"
            f"export const omniaMaxConfig = {data} as const;\n"
            "export type OmniaMaxConfig = typeof omniaMaxConfig;\n"
        ),
        "src/app/api/omnia/config/route.ts": """import { NextResponse } from "next/server";

import { omniaMaxConfig } from "@/lib/omnia/max-config";

export const dynamic = "force-static";

export function GET() {
  return NextResponse.json(omniaMaxConfig, {
    headers: { "Cache-Control": "public, max-age=60, stale-while-revalidate=300" },
  });
}
""",
        "src/app/legal/privacy/page.tsx": """import { omniaMaxConfig as app } from "@/lib/omnia/max-config";

export const metadata = { title: `Политика конфиденциальности — ${app.app_name}` };

export default function PrivacyPage() {
  const operator = app.operator.legal_name || app.app_name;
  return (
    <main style={{ maxWidth: 760, margin: "0 auto", padding: "32px 20px 64px", lineHeight: 1.65 }}>
      <h1>Политика конфиденциальности</h1>
      <p><strong>Оператор:</strong> {operator}</p>
      {app.operator.inn && <p><strong>ИНН:</strong> {app.operator.inn}</p>}
      {app.operator.address && <p><strong>Адрес:</strong> {app.operator.address}</p>}
      <h2>Какие данные обрабатываются</h2>
      <p>
        Приложение получает от MAX идентификатор пользователя и доступные данные профиля,
        необходимые для входа и работы функций приложения. Действия, заказы, записи и
        обращения сохраняются только в объёме, необходимом для оказания услуги.
      </p>
      <h2>Цели и срок обработки</h2>
      <p>
        Данные используются для исполнения запросов пользователя, поддержки, безопасности
        и улучшения сервиса. Они хранятся не дольше, чем требуют эти цели и закон.
      </p>
      <h2>Права пользователя</h2>
      <p>
        Пользователь может запросить сведения, исправление или удаление данных через
        страницу поддержки. Согласие на необязательные уведомления можно отозвать.
      </p>
      <p>Возрастная маркировка: {app.legal.age_rating}.</p>
      <p>Дата актуализации: {new Date().toLocaleDateString("ru-RU")}.</p>
    </main>
  );
}
""",
        "src/app/legal/terms/page.tsx": """import { omniaMaxConfig as app } from "@/lib/omnia/max-config";

export const metadata = { title: `Условия использования — ${app.app_name}` };

export default function TermsPage() {
  const operator = app.operator.legal_name || app.app_name;
  return (
    <main style={{ maxWidth: 760, margin: "0 auto", padding: "32px 20px 64px", lineHeight: 1.65 }}>
      <h1>Условия использования</h1>
      <p>
        Эти условия регулируют использование мини-приложения «{app.app_name}».
        Владелец сервиса: {operator}.
      </p>
      <h2>Возможности сервиса</h2>
      <p>{app.summary}</p>
      <h2>Правила</h2>
      <p>
        Нельзя нарушать закон, права других лиц, пытаться получить чужие данные,
        вмешиваться в работу сервиса или использовать его для спама и обмана.
      </p>
      {app.legal.has_sales && (
        <>
          <h2>Заказы и оплата</h2>
          <p>
            Итоговая цена, состав заказа, способ оплаты, отмены и возврата показываются
            до подтверждения. Платёж обрабатывает указанный при оформлении провайдер.
          </p>
        </>
      )}
      {app.legal.has_user_content && (
        <>
          <h2>Пользовательский контент</h2>
          <p>
            Запрещён незаконный и оскорбительный контент. Владелец вправе ограничить
            доступ и удалить нарушение; жалобу можно отправить через поддержку.
          </p>
        </>
      )}
      <p>Возрастная маркировка: {app.legal.age_rating}.</p>
    </main>
  );
}
""",
        "src/app/support/page.tsx": """import { omniaMaxConfig as app } from "@/lib/omnia/max-config";

export const metadata = { title: `Поддержка — ${app.app_name}` };

export default function SupportPage() {
  return (
    <main style={{ maxWidth: 680, margin: "0 auto", padding: "32px 20px 64px", lineHeight: 1.65 }}>
      <h1>Поддержка</h1>
      <p>Опишите проблему, ожидаемый результат и время, когда она возникла.</p>
      {app.support.email && <p><strong>Email:</strong> <a href={`mailto:${app.support.email}`}>{app.support.email}</a></p>}
      {app.support.phone && <p><strong>Телефон:</strong> <a href={`tel:${app.support.phone}`}>{app.support.phone}</a></p>}
      <p>{app.support.response_time}</p>
      <nav style={{ display: "flex", gap: 16, flexWrap: "wrap", marginTop: 28 }}>
        <a href="/legal/privacy">Конфиденциальность</a>
        <a href="/legal/terms">Условия использования</a>
      </nav>
    </main>
  );
}
""",
    }
