"""Runnable export (P5) — assemble a COMPLETE, runnable repo for a container app.

`GET /projects/{id}/download` zips the project's git snapshot. For a STATIC/code
project that IS the whole app. But a CONTAINER stack (nextjs-postgres-drizzle /
nextjs-realtime / fastapi-postgres / nextjs-entities) keeps in git ONLY the
writer-generated files — the runnable skeleton (engine, kit, package.json,
configs, Dockerfile, migrations harness) lives in the template/image, NOT in git.
So a downloaded container-app zip is the generated files alone: not runnable. The
owner's «это настоящий код, забери его» moment then hands the user an incomplete
repo.

This composes the real, runnable repo: the skeleton template tree OVERLAID with
the writer's generated files (generated wins on conflict) + a short README. Pure
+ deterministic (:func:`read_template_tree` / :func:`build_runnable_export`) so it
is unit-tested against a temp dir with no container. Gated by
``Settings.use_full_container_export`` and FAIL-SOFT at the call site: if the
template tree isn't present (e.g. not shipped into the api image yet) it yields an
empty overlay and the caller falls back to the snapshot-only zip — so enabling
this can never produce a WORSE download than today.
"""

from __future__ import annotations

import json
from pathlib import Path

# apps/api/src/omnia_api/services/ -> parents[4] == apps/  (same as agent_builder)
_TEMPLATES_DIR = Path(__file__).resolve().parents[4] / "orchestrator" / "templates"

# Never export build artifacts / dependency trees / VCS — they bloat the zip and
# are regenerated by `npm install` / `docker build`.
_IGNORE_DIRS = frozenset(
    {"node_modules", ".next", ".git", "__pycache__", "dist", ".turbo", ".vercel", ".omnia"}
)
# Skip a single absurdly large file (a stray binary) so one blob can't bloat the zip.
_MAX_FILE_BYTES = 512_000

_README = """# Экспорт проекта Omnia

Это НАСТОЯЩИЙ код твоего приложения — фиксированный скелет (бэкенд, движок, кит,
конфиги) + сгенерированные тобой файлы поверх. Запуск:

```bash
# 1. зависимости
npm install          # или: pip install -r requirements.txt  (для fastapi)
# 2. база и переменные окружения
cp .env.example .env # заполни DATABASE_URL и секреты
# 3. миграции (если есть)
npm run db:migrate   # drizzle  /  alembic upgrade head  (fastapi)
# 4. запуск
npm run dev          # или: uvicorn app.main:app --reload
```

Полный стек одной командой — `docker compose up` (если в проекте есть compose).
Сгенерированные файлы можно править как обычный код; скелет менять не обязательно.
"""


def _shared_asset_path(shared: Path, relative: str) -> Path:
    path = shared / relative
    for ancestor in (path, *path.parents):
        if ancestor == shared.parent:
            break
        if ancestor.is_symlink():
            raise ValueError("invalid shared source symlink")
    if not path.resolve().is_relative_to(shared.resolve()):
        raise ValueError("invalid shared source containment")
    if not path.is_file():
        raise FileNotFoundError(f"shared template asset unavailable: {relative}")
    return path


def _validate_source_path(relative: str) -> None:
    if (
        not relative.startswith("src/")
        or "\\" in relative
        or any(part in {"", ".", ".."} or ":" in part for part in relative.split("/"))
        or Path(relative).suffix not in {".ts", ".tsx"}
    ):
        raise ValueError("invalid shared source path")


def read_template_tree(template_dir: Path) -> dict[str, str | bytes]:
    """Read a skeleton template tree into ``{repo-relative path: content}``,
    skipping dependency/build/VCS dirs and oversized blobs. Text decodes to str;
    anything non-UTF-8 stays bytes. Missing dir → empty dict (fail-soft)."""
    out: dict[str, str | bytes] = {}
    if not template_dir.is_dir():
        return out
    for p in template_dir.rglob("*"):
        if not p.is_file():
            continue
        rel_parts = p.relative_to(template_dir).parts
        if any(part in _IGNORE_DIRS for part in rel_parts):
            continue
        try:
            if p.stat().st_size > _MAX_FILE_BYTES:
                continue
            data = p.read_bytes()
        except OSError:
            continue
        rel = "/".join(rel_parts)
        try:
            out[rel] = data.decode("utf-8")
        except UnicodeDecodeError:
            out[rel] = data
    # Only our mounted/source collection has shared data. Arbitrary complete
    # template directories and historical exports keep their own bytes.
    if template_dir.resolve().parent == _TEMPLATES_DIR.resolve():
        shared = _TEMPLATES_DIR / "shared-public"
        manifest = json.loads((shared / "manifest.json").read_text(encoding="utf-8"))
        if template_dir.name in manifest["templates"]:
            for name in manifest["assets"]:
                if not isinstance(name, str) or Path(name).name != name or not name.endswith(".js"):
                    raise ValueError("invalid shared public asset name")
                asset = _shared_asset_path(shared, name)
                out[f"public/{name}"] = asset.read_bytes().decode("utf-8")
            for relative, templates in manifest.get("source_files", {}).items():
                if template_dir.name in templates:
                    _validate_source_path(relative)
                    asset = _shared_asset_path(shared, f"source/{relative}")
                    out[relative] = asset.read_bytes().decode("utf-8")
    return out


def build_runnable_export(
    template_name: str,
    generated: dict[str, str | bytes],
    *,
    templates_root: Path | None = None,
) -> dict[str, str | bytes]:
    """Compose a runnable repo: the skeleton (``templates/<template_name>``)
    OVERLAID with the writer's ``generated`` files (generated wins on conflict),
    plus a README if the project doesn't already ship one.

    Returns ONLY the ``generated`` files (a no-op overlay) when the skeleton tree
    is absent — so the caller's fallback keeps today's behaviour. Pure."""
    root = (templates_root or _TEMPLATES_DIR) / template_name
    tree = read_template_tree(root)
    if not tree:
        return dict(generated)  # skeleton unavailable → no worse than snapshot-only
    tree.update(generated)  # the writer's files override the skeleton
    tree.setdefault("README.omnia.md", _README)
    return tree
